"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-03 23:27:51.353180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cat_data_sources',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('system_name', sa.String(length=128), nullable=False),
    sa.Column('system_type', sa.Enum('ORACLE', 'SAP_ECC', 'SAP_S4HANA', 'MSSQL', 'FLAT_FILE', name='system_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('target_type', sa.Enum('SOURCE', 'STAGING', 'TARGET', name='target_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('connection_config', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cat_data_sources')),
    sa.UniqueConstraint('system_name', name='uq_cat_data_sources_system_name')
    )
    op.create_table('cat_tables',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(length=128), nullable=False),
    sa.Column('business_name', sa.String(length=256), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('row_count_estimate', sa.BigInteger(), nullable=True),
    sa.Column('last_profiled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('business_object', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('row_count_estimate IS NULL OR row_count_estimate >= 0', name=op.f('ck_cat_tables_row_count_non_negative')),
    sa.ForeignKeyConstraint(['source_id'], ['cat_data_sources.id'], name=op.f('fk_cat_tables_source_id_cat_data_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cat_tables')),
    sa.UniqueConstraint('source_id', 'table_name', name='uq_cat_tables_source_id_table_name')
    )
    op.create_index('ix_cat_tables_business_object', 'cat_tables', ['business_object'], unique=False)
    op.create_table('cat_columns',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('column_name', sa.String(length=128), nullable=False),
    sa.Column('data_type', sa.String(length=64), nullable=False),
    sa.Column('char_max_length', sa.Integer(), nullable=True),
    sa.Column('numeric_precision', sa.Integer(), nullable=True),
    sa.Column('numeric_scale', sa.Integer(), nullable=True),
    sa.Column('is_nullable', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_primary_key', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('pii_classification', sa.Enum('PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'RESTRICTED_PII', name='pii_classification', native_enum=False, create_constraint=True, length=32), server_default='INTERNAL', nullable=False),
    sa.Column('sample_values', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('null_ratio', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('distinct_ratio', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('ordinal_position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('check_table', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('NOT (is_primary_key AND is_nullable)', name=op.f('ck_cat_columns_pk_not_nullable')),
    sa.CheckConstraint('char_max_length IS NULL OR char_max_length > 0', name=op.f('ck_cat_columns_char_length_positive')),
    sa.CheckConstraint('distinct_ratio IS NULL OR distinct_ratio BETWEEN 0 AND 1', name=op.f('ck_cat_columns_distinct_ratio_range')),
    sa.CheckConstraint('null_ratio IS NULL OR null_ratio BETWEEN 0 AND 1', name=op.f('ck_cat_columns_null_ratio_range')),
    sa.CheckConstraint('numeric_precision IS NULL OR numeric_precision > 0', name=op.f('ck_cat_columns_precision_positive')),
    sa.CheckConstraint('numeric_scale IS NULL OR (numeric_precision IS NOT NULL AND numeric_scale >= 0 AND numeric_scale <= numeric_precision)', name=op.f('ck_cat_columns_scale_within_precision')),
    sa.ForeignKeyConstraint(['table_id'], ['cat_tables.id'], name=op.f('fk_cat_columns_table_id_cat_tables'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cat_columns')),
    sa.UniqueConstraint('table_id', 'column_name', name='uq_cat_columns_table_id_column_name')
    )
    op.create_table('map_table_rules',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('source_table_id', sa.Integer(), nullable=False),
    sa.Column('target_table_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', name='mapping_status', native_enum=False, create_constraint=True, length=32), server_default='DRAFT', nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('approved_by', sa.String(length=128), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status <> 'APPROVED' OR (approved_by IS NOT NULL AND approved_at IS NOT NULL)", name=op.f('ck_map_table_rules_approved_requires_approver')),
    sa.CheckConstraint('approved_by IS NULL OR approved_by <> created_by', name=op.f('ck_map_table_rules_maker_checker_separation')),
    sa.CheckConstraint('source_table_id <> target_table_id', name=op.f('ck_map_table_rules_source_ne_target')),
    sa.CheckConstraint('version >= 1', name=op.f('ck_map_table_rules_version_positive')),
    sa.ForeignKeyConstraint(['source_table_id'], ['cat_tables.id'], name=op.f('fk_map_table_rules_source_table_id_cat_tables'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['target_table_id'], ['cat_tables.id'], name=op.f('fk_map_table_rules_target_table_id_cat_tables'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_map_table_rules')),
    sa.UniqueConstraint('source_table_id', 'target_table_id', 'version', name='uq_map_table_rules_src_tgt_version')
    )
    op.create_table('map_field_rules',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('mapping_set_id', sa.Integer(), nullable=False),
    sa.Column('source_column_id', sa.Integer(), nullable=True),
    sa.Column('target_column_id', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.Enum('DIRECT_COPY', 'VALUE_MAPPING', 'SQL_EXPRESSION', 'PYTHON_SNIPPET', 'STATIC_VALUE', name='rule_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('transformation_logic', sa.Text(), nullable=True),
    sa.Column('ai_suggested', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('ai_model_name', sa.String(length=128), nullable=True),
    sa.Column('ai_confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('ai_reasoning', sa.Text(), nullable=True),
    sa.Column('is_mandatory_target', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("rule_type NOT IN ('DIRECT_COPY', 'VALUE_MAPPING') OR source_column_id IS NOT NULL", name=op.f('ck_map_field_rules_copy_rules_need_source')),
    sa.CheckConstraint("rule_type NOT IN ('SQL_EXPRESSION', 'PYTHON_SNIPPET', 'STATIC_VALUE') OR transformation_logic IS NOT NULL", name=op.f('ck_map_field_rules_logic_rules_need_logic')),
    sa.CheckConstraint('NOT ai_suggested OR ai_model_name IS NOT NULL', name=op.f('ck_map_field_rules_ai_requires_model')),
    sa.CheckConstraint('ai_confidence_score IS NULL OR ai_confidence_score BETWEEN 0 AND 1', name=op.f('ck_map_field_rules_ai_confidence_range')),
    sa.ForeignKeyConstraint(['mapping_set_id'], ['map_table_rules.id'], name=op.f('fk_map_field_rules_mapping_set_id_map_table_rules'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_column_id'], ['cat_columns.id'], name=op.f('fk_map_field_rules_source_column_id_cat_columns'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['target_column_id'], ['cat_columns.id'], name=op.f('fk_map_field_rules_target_column_id_cat_columns'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_map_field_rules')),
    sa.UniqueConstraint('mapping_set_id', 'target_column_id', name='uq_map_field_rules_set_target_column')
    )
    op.create_table('mig_migration_runs',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('mapping_set_id', sa.Integer(), nullable=False),
    sa.Column('wave_name', sa.String(length=128), nullable=False),
    sa.Column('current_phase', sa.Enum('EXTRACT', 'PROFILE', 'TRANSFORM', 'VALIDATE', 'LOAD', 'RECONCILE', 'COMPLETE', name='migration_phase', native_enum=False, create_constraint=True, length=32), server_default='EXTRACT', nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED', name='run_status', native_enum=False, create_constraint=True, length=32), server_default='PENDING', nullable=False),
    sa.Column('records_extracted', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('records_transformed', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('records_loaded', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('records_failed', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('completed_at IS NULL OR started_at IS NULL OR completed_at >= started_at', name=op.f('ck_mig_migration_runs_completed_after_started')),
    sa.CheckConstraint('records_extracted >= 0 AND records_transformed >= 0 AND records_loaded >= 0 AND records_failed >= 0', name=op.f('ck_mig_migration_runs_counters_non_negative')),
    sa.ForeignKeyConstraint(['mapping_set_id'], ['map_table_rules.id'], name=op.f('fk_mig_migration_runs_mapping_set_id_map_table_rules'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mig_migration_runs'))
    )
    op.create_index('ix_mig_migration_runs_mapping_set_id', 'mig_migration_runs', ['mapping_set_id'], unique=False)
    op.create_table('gov_defect_aggregates',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('field_rule_id', sa.Integer(), nullable=False),
    sa.Column('rule_signature', sa.String(length=256), nullable=False),
    sa.Column('violation_count', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('sample_failing_record_ids', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('jira_issue_key', sa.String(length=32), nullable=True),
    sa.Column('jira_status', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('violation_count >= 0', name=op.f('ck_gov_defect_aggregates_violation_count_non_negative')),
    sa.ForeignKeyConstraint(['field_rule_id'], ['map_field_rules.id'], name=op.f('fk_gov_defect_aggregates_field_rule_id_map_field_rules'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_id'], ['mig_migration_runs.id'], name=op.f('fk_gov_defect_aggregates_run_id_mig_migration_runs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gov_defect_aggregates')),
    sa.UniqueConstraint('run_id', 'field_rule_id', 'rule_signature', name='uq_gov_defect_aggregates_run_rule_sig')
    )
    op.create_table('map_value_lookups',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('field_rule_id', sa.Integer(), nullable=False),
    sa.Column('source_value', sa.String(length=512), nullable=False),
    sa.Column('target_value', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['field_rule_id'], ['map_field_rules.id'], name=op.f('fk_map_value_lookups_field_rule_id_map_field_rules'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_map_value_lookups')),
    sa.UniqueConstraint('field_rule_id', 'source_value', name='uq_map_value_lookups_rule_source_value')
    )
    op.create_table('mig_cell_lineage',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('source_pk_value', sa.String(length=512), nullable=False),
    sa.Column('target_pk_value', sa.String(length=512), nullable=True),
    sa.Column('target_column_name', sa.String(length=128), nullable=False),
    sa.Column('source_raw_value', sa.Text(), nullable=True),
    sa.Column('transformed_value', sa.Text(), nullable=True),
    sa.Column('rule_applied_id', sa.Integer(), nullable=True),
    sa.Column('loaded_successfully', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rule_applied_id'], ['map_field_rules.id'], name=op.f('fk_mig_cell_lineage_rule_applied_id_map_field_rules'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_id'], ['mig_migration_runs.id'], name=op.f('fk_mig_cell_lineage_run_id_mig_migration_runs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mig_cell_lineage'))
    )
    op.create_index('ix_mig_cell_lineage_rule_applied_id', 'mig_cell_lineage', ['rule_applied_id'], unique=False)
    op.create_index('ix_mig_cell_lineage_run_id_source_pk_value', 'mig_cell_lineage', ['run_id', 'source_pk_value'], unique=False)
    op.create_index('ix_mig_cell_lineage_run_id_target_pk_value', 'mig_cell_lineage', ['run_id', 'target_pk_value'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mig_cell_lineage_run_id_target_pk_value', table_name='mig_cell_lineage')
    op.drop_index('ix_mig_cell_lineage_run_id_source_pk_value', table_name='mig_cell_lineage')
    op.drop_index('ix_mig_cell_lineage_rule_applied_id', table_name='mig_cell_lineage')
    op.drop_table('mig_cell_lineage')
    op.drop_table('map_value_lookups')
    op.drop_table('gov_defect_aggregates')
    op.drop_index('ix_mig_migration_runs_mapping_set_id', table_name='mig_migration_runs')
    op.drop_table('mig_migration_runs')
    op.drop_table('map_field_rules')
    op.drop_table('map_table_rules')
    op.drop_table('cat_columns')
    op.drop_index('ix_cat_tables_business_object', table_name='cat_tables')
    op.drop_table('cat_tables')
    op.drop_table('cat_data_sources')
    # ### end Alembic commands ###
